Repository SSAF-SOUND/ssaf-sound-be, pull requests merged in 2023-07, with the labels that each got.

#99 feat: 게시글 목록 조회 N+1 해결 및 쿼리 최적화 구현
  .gitignore
  src/main/java/com/ssafy/ssafsound/domain/board/controller/BoardController.java
  src/main/java/com/ssafy/ssafsound/domain/board/dto/GetBoardElement.java
  src/main/java/com/ssafy/ssafsound/domain/board/dto/GetBoardListResDto.java
  src/main/java/com/ssafy/ssafsound/domain/board/dto/GetBoardResDto.java
  src/main/java/com/ssafy/ssafsound/domain/board/exception/BoardErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/board/service/BoardService.java
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostDetailResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostElement.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostListResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
  src/main/resources/application-local.yml
Labels: fix, refactor

#101 feat: 핫 게시글 목록 조회 기능 구현
  src/main/java/com/ssafy/ssafsound/batch/tasklet/PostTasklet.java
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetHotPostElement.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetHotPostResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
Labels: feature

#104 feat: 리크루트 목록 조회 페이지 조회 기능 작성
  src/main/java/com/ssafy/ssafsound/domain/meta/controller/MetaDataController.java
  src/main/java/com/ssafy/ssafsound/domain/meta/dto/GetCampusesResDto.java
  src/main/java/com/ssafy/ssafsound/domain/meta/dto/GetRecruitTypeResDto.java
  src/main/java/com/ssafy/ssafsound/domain/meta/dto/GetSkillsResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitsReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitsResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/Participant.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitParticipant.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitSkillElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
  src/main/resources/application-local.yml
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
Labels: feature

#109 feat: 나의 게시글 목록 조회 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/board/exception/BoardErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/board/service/BoardService.java
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotElement.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostMyElement.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostMyResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
Labels: fix, feature, refactor

#110 feat: 댓글 작성 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/CommentNumber.java
  src/main/java/com/ssafy/ssafsound/domain/comment/dto/PostCommentWriteReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/comment/exception/CommentErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/comment/exception/CommentException.java
  src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentNumberRepository.java
  src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentRepository.java
  src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
Labels: feature

#111 feat: 싸피생 인증 추가
  src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/PostCertificationInfoReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/PostCertificationInfoResDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/Certification.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/MetaDataType.java
  src/main/java/com/ssafy/ssafsound/domain/meta/service/EnumMetaDataConsumer.java
  src/test/java/com/ssafy/ssafsound/domain/member/service/MemberServiceTest.java
Labels: feature, test

#115 fix : SSAFY Info 수정에 따른 Response Body 데이터 변경
  src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthenticationArgumentResolver.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/controller/RecruitCommentController.java
  src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
Labels: fix

#114 feat: 대댓글 작성 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
  src/main/java/com/ssafy/ssafsound/domain/comment/dto/PostCommentWriteReplyReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/comment/exception/CommentErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
Labels: feature

#125 refactor: 싸피생 인증 로직 리팩토링 및 SSAFYInfo DTO 생성 리팩토링
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MajorType.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberResDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/PostCertificationInfoReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/PostCertificationInfoResDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/SSAFYInfo.java
  src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
  src/main/java/com/ssafy/ssafsound/domain/meta/converter/MajorTrackConverter.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/MajorTrack.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/MetaDataType.java
  src/main/java/com/ssafy/ssafsound/domain/meta/service/EnumMetaDataConsumer.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitApplicationElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/RecruitCommentElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/repository/RecruitCommentRepository.java
  src/test/java/com/ssafy/ssafsound/domain/member/service/MemberServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentServiceTest.java
Labels: fix, refactor, test

#127 feat: 게시글 검색 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostSearchElement.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostSearchReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostSearchResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
Labels: feature

#119 feat: 댓글 수정 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
  src/main/java/com/ssafy/ssafsound/domain/comment/dto/PutCommentUpdateReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/comment/exception/CommentErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
Labels: feature

#134 feat: 댓글 목록 조회 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
  src/main/java/com/ssafy/ssafsound/domain/comment/dto/GetCommentElement.java
  src/main/java/com/ssafy/ssafsound/domain/comment/dto/GetCommentResDto.java
  src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentRepository.java
  src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
Labels: feature

#137 feat: 댓글 삭제 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
  src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
Labels: feature

#142 test : 점심 메뉴 테스트 및 리팩토링
  src/main/java/com/ssafy/ssafsound/domain/lunch/controller/LunchController.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/domain/LunchPoll.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/repository/LunchPollRepository.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchPollService.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchService.java
  src/main/java/com/ssafy/ssafsound/global/config/TimeConfig.java
  src/main/resources/application.yml
  src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchPollServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchServiceTest.java
  src/test/java/com/ssafy/ssafsound/global/util/NullableConverter.java
Labels: refactor, test

#139 feat: 댓글 좋아요 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/BaseTimeEntity.java
  src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
  src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentLikeRepository.java
  src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
Labels: feature

#143 feat: Hot 게시글 검색 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotSearchReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostSearchElement.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostSearchResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
Labels: feature

#141 feat: member input portfolio
  src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberLink.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberProfile.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/PutMemberLink.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/PutMemberProfileReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberLinkRepository.java
  src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberProfileRepository.java
  src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberSkillRepository.java
  src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
Labels: feature

#147 fix: 충돌 해결로 인한 오탈자 수정
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
  src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
Labels: fix

#144 feat: 리크루트 완료 기능 추가
  src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Recruit.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitDynamicQueryRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/task/RecruitCron.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
Labels: feature

#151 refactor: 게시글 관련 리팩토링 완료
  src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
  src/main/java/com/ssafy/ssafsound/domain/comment/dto/GetCommentElement.java
  src/main/java/com/ssafy/ssafsound/domain/comment/dto/GetCommentResDto.java
  src/main/java/com/ssafy/ssafsound/domain/comment/dto/PostCommentWriteReplyReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentLikeRepository.java
  src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostDetailElement.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostDetailListResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostDetailResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/ImageInfo.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/ImageUrl.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/ImageUrlElement.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/PostPostWriteReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/PostPutUpdateReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/main/java/com/ssafy/ssafsound/global/validator/CheckImageInfo.java
  src/main/java/com/ssafy/ssafsound/global/validator/ImageInfoValidator.java
Labels: refactor

#152 feat: member get portfolio
  src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberProfile.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberPortfolioResDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/PutMemberProfileReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberRepository.java
  src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
  src/main/java/com/ssafy/ssafsound/global/interceptor/AuthInterceptor.java
Labels: feature

#154 feat: 멤버 프로필 조회 및 포트폴리오 공개 여부에 따른 로직 리팩토링
  src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberPortfolioResDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberProfileResDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/PortfolioElement.java
  src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
Labels: feature, refactor

#159 refactor: 리크루트 참여자 조회 수정
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/GetRecruitLimitDetail.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitLimitationRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitParticipantsResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/ParticipantElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
  src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
Labels: refactor, test

#155 feat : 채팅방 조회 api 추가
  .gitignore
  src/main/java/com/ssafy/ssafsound/domain/chat/controller/ChatController.java
  src/main/java/com/ssafy/ssafsound/domain/chat/domain/Chat.java
  src/main/java/com/ssafy/ssafsound/domain/chat/domain/ChatRoom.java
  src/main/java/com/ssafy/ssafsound/domain/chat/domain/Talker.java
  src/main/java/com/ssafy/ssafsound/domain/chat/dto/ChatRoomElementDto.java
  src/main/java/com/ssafy/ssafsound/domain/chat/dto/DeleteChatReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/chat/dto/DeleteChatResDto.java
  src/main/java/com/ssafy/ssafsound/domain/chat/dto/GetChatRoomsResDto.java
  src/main/java/com/ssafy/ssafsound/domain/chat/dto/LatestChatDto.java
  src/main/java/com/ssafy/ssafsound/domain/chat/dto/PatchChatReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/chat/dto/PatchChatResDto.java
  src/main/java/com/ssafy/ssafsound/domain/chat/dto/TalkerInfoDto.java
  src/main/java/com/ssafy/ssafsound/domain/chat/exception/ChatErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/chat/exception/ChatException.java
  src/main/java/com/ssafy/ssafsound/domain/chat/repository/ChatRepository.java
  src/main/java/com/ssafy/ssafsound/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/ssafy/ssafsound/domain/chat/repository/TalkerRepository.java
  src/main/java/com/ssafy/ssafsound/domain/chat/service/ChatRoomService.java
  src/main/java/com/ssafy/ssafsound/domain/chat/service/ChatService.java
  src/main/java/com/ssafy/ssafsound/domain/meta/converter/SourceTypeConverter.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/MetaDataType.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/SourceType.java
  src/main/java/com/ssafy/ssafsound/domain/meta/service/EnumMetaDataConsumer.java
  src/main/resources/application-local.yml
Labels: feature

#161 refactor: 리크루트 수정
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitLimitation.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitLimitationRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitSkillRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
Labels: refactor

#162 feat : 채팅방 삭제 api 추가
  src/main/java/com/ssafy/ssafsound/domain/chat/controller/ChatController.java
  src/main/java/com/ssafy/ssafsound/domain/chat/domain/Talker.java
  src/main/java/com/ssafy/ssafsound/domain/chat/dto/DeleteChatResDto.java
  src/main/java/com/ssafy/ssafsound/domain/chat/exception/ChatErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/chat/exception/ChatException.java
  src/main/java/com/ssafy/ssafsound/domain/chat/repository/TalkerRepository.java
  src/main/java/com/ssafy/ssafsound/domain/chat/service/ChatRoomService.java
Labels: feature

#171 refactor: presigned url upload 도입
  src/main/java/com/ssafy/ssafsound/infra/storage/StorageController.java
  src/main/java/com/ssafy/ssafsound/infra/storage/dto/ImagePathDto.java
  src/main/java/com/ssafy/ssafsound/infra/storage/dto/PostStoreImageResDto.java
  src/main/java/com/ssafy/ssafsound/infra/storage/service/AwsS3PreSignerService.java
Labels: feature

#165 refactor: 댓글 관련 리팩토링
  src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
  src/main/java/com/ssafy/ssafsound/domain/comment/dto/GetCommentElement.java
  src/main/java/com/ssafy/ssafsound/domain/comment/dto/GetCommentResDto.java
  src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentRepository.java
  src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
Labels: refactor

#167 refactor: 리크루트 스크랩 리팩토링
  src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitLimitDetail.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/Participant.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitScrapCountResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitParticipant.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitScrapRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/ParticipantElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitApplicationElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/PostRecruitCommentResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/RecruitCommentElement.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentServiceTest.java
Labels: refactor
