Repository SSAF-SOUND/ssaf-sound-be, pull requests merged in 2023-10, with the labels that each got.

#262 feat: member 회원 탈퇴 기능 및 AOP 수정
  build.gradle
  src/docs/asciidoc/member.adoc
  src/main/java/com/ssafy/ssafsound/domain/event/MemberLeavedEvent.java
  src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/AccountState.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/main/java/com/ssafy/ssafsound/global/aspect/LoggingAspect.java
  src/test/java/com/ssafy/ssafsound/domain/member/controller/MemberControllerTest.java
  src/test/java/com/ssafy/ssafsound/domain/member/service/MemberServiceTest.java
Labels: fix, feature

#263 test: 게시글 쓰기 단위 테스트 코드 구현
  src/main/java/com/ssafy/ssafsound/domain/board/dto/GetBoardElement.java
  src/main/java/com/ssafy/ssafsound/domain/board/repository/BoardRepository.java
  src/main/java/com/ssafy/ssafsound/domain/board/service/BoardService.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/PostImage.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/ImageInfo.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
  src/test/java/com/ssafy/ssafsound/domain/board/controller/BoardControllerTest.java
  src/test/java/com/ssafy/ssafsound/domain/board/service/BoardServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/post/service/PostServiceTest.java
  src/test/java/com/ssafy/ssafsound/global/util/fixture/BoardFixture.java
  src/test/java/com/ssafy/ssafsound/global/util/fixture/PostFixture.java
Labels: fix, test

#265 fix: 페이지네이션 cursor 버그 수정
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostReqDto.java
Labels: fix

#267 fix : cron 요일 수정
  src/main/java/com/ssafy/ssafsound/domain/lunch/task/LunchScraper.java
Labels: fix

#269 fix: 댓글 조회 버그 수정
  src/main/java/com/ssafy/ssafsound/domain/comment/dto/GetCommentResDto.java
Labels: fix

#270 fix: 페이지네이션 cursor 버그 수정
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostMyReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostSearchReqDto.java
Labels: fix

#273 fix: 리크루트 목록 조회 모집종료 조건 누락 수정
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitDynamicQueryRepositoryImpl.java
Labels: fix

#276 test: TermService test code 추가
  build.gradle
  src/test/java/com/ssafy/ssafsound/domain/term/controller/TermControllerTest.java
  src/test/java/com/ssafy/ssafsound/domain/term/service/TermServiceTest.java
  src/test/java/com/ssafy/ssafsound/global/util/fixture/TermFixture.java
Labels: test

#295 fix: recruit 업데이트시, limitation값 반영되지 않는 오류 수정
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
Labels: fix

#300 fix: 댓글 삭제 시 댓글 수가 반영되지 않는 버그 수정
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostElement.java
Labels: fix, hotfix

#302 fix: Hot 게시글 삭제 batch -> scheduler로 수정, 삭제 쿼리 수정
  src/main/java/com/ssafy/ssafsound/batch/config/PostBatchConfig.java
  src/main/java/com/ssafy/ssafsound/batch/scheduler/PostScheduler.java
  src/main/java/com/ssafy/ssafsound/batch/tasklet/PostTasklet.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostCustomRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostCustomRepositoryImpl.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/scheduler/PostScheduler.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
Labels: fix, refactor

#303 fix: 게시글 상세보기에도 댓글 수 버그 수정
  src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostDetailElement.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostElement.java
Labels: fix, refactor
