Repository SSAF-SOUND/ssaf-sound-be, pull requests merged in 2023-11, with the labels that each got.

#307 feat: 전체 게시글 목록 조회 기능 구현
  build.gradle
  src/docs/asciidoc/post.adoc
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
  src/main/java/com/ssafy/ssafsound/global/validator/CheckFileCount.java
  src/main/java/com/ssafy/ssafsound/global/validator/CheckFileSize.java
  src/main/java/com/ssafy/ssafsound/global/validator/CheckImage.java
  src/main/java/com/ssafy/ssafsound/global/validator/FileCountValidator.java
  src/main/java/com/ssafy/ssafsound/global/validator/FileSizeValidator.java
  src/main/java/com/ssafy/ssafsound/global/validator/ImageValidator.java
  src/main/resources/static/docs/index.html
  src/test/java/com/ssafy/ssafsound/domain/post/controller/PostControllerTest.java
  src/test/java/com/ssafy/ssafsound/domain/post/service/PostServiceTest.java
  src/test/java/com/ssafy/ssafsound/global/util/fixture/PostFixture.java
Labels: feature

#309 feat: 전체 게시글 목록 조회 기능 구현
  build.gradle
  src/docs/asciidoc/post.adoc
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
  src/main/java/com/ssafy/ssafsound/global/validator/CheckFileCount.java
  src/main/java/com/ssafy/ssafsound/global/validator/CheckFileSize.java
  src/main/java/com/ssafy/ssafsound/global/validator/CheckImage.java
  src/main/java/com/ssafy/ssafsound/global/validator/FileCountValidator.java
  src/main/java/com/ssafy/ssafsound/global/validator/FileSizeValidator.java
  src/main/java/com/ssafy/ssafsound/global/validator/ImageValidator.java
  src/main/resources/static/docs/index.html
  src/test/java/com/ssafy/ssafsound/domain/post/controller/PostControllerTest.java
  src/test/java/com/ssafy/ssafsound/domain/post/service/PostServiceTest.java
  src/test/java/com/ssafy/ssafsound/global/util/fixture/PostFixture.java
Labels: feature

#311 fix : 점심 투표 정책 변경
  src/main/java/com/ssafy/ssafsound/domain/lunch/repository/LunchPollRepository.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchPollService.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchService.java
  src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchPollServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchServiceTest.java
Labels: fix

#305 docs: readMe 문서 업데이트
  README.md
  picture/logo.png
  picture/ssafsound architecture.jpg
Labels: docs

#314 feat: 알림 관련 기능 구현
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/notification.adoc
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
  src/main/java/com/ssafy/ssafsound/domain/comment/exception/CommentErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentRepository.java
  src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
  src/main/java/com/ssafy/ssafsound/domain/notification/controller/NotificationController.java
  src/main/java/com/ssafy/ssafsound/domain/notification/converter/NotificationTypeConverter.java
  src/main/java/com/ssafy/ssafsound/domain/notification/converter/ServiceTypeConverter.java
  src/main/java/com/ssafy/ssafsound/domain/notification/domain/AutoIncrementSequence.java
  src/main/java/com/ssafy/ssafsound/domain/notification/domain/Notification.java
  src/main/java/com/ssafy/ssafsound/domain/notification/domain/NotificationType.java
  src/main/java/com/ssafy/ssafsound/domain/notification/domain/ServiceType.java
  src/main/java/com/ssafy/ssafsound/domain/notification/dto/GetCheckNotificationResDto.java
  src/main/java/com/ssafy/ssafsound/domain/notification/dto/GetNotificationElement.java
  src/main/java/com/ssafy/ssafsound/domain/notification/dto/GetNotificationReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/notification/dto/GetNotificationResDto.java
  src/main/java/com/ssafy/ssafsound/domain/notification/event/NotificationEvent.java
  src/main/java/com/ssafy/ssafsound/domain/notification/event/NotificationEventListener.java
  src/main/java/com/ssafy/ssafsound/domain/notification/exception/NotificationErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/notification/exception/NotificationException.java
  src/main/java/com/ssafy/ssafsound/domain/notification/message/NotificationMessage.java
  src/main/java/com/ssafy/ssafsound/domain/notification/repository/NotificationCustomRepository.java
  src/main/java/com/ssafy/ssafsound/domain/notification/repository/NotificationRepository.java
  src/main/java/com/ssafy/ssafsound/domain/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/ssafy/ssafsound/domain/notification/service/NotificationService.java
  src/main/java/com/ssafy/ssafsound/domain/notification/service/SequenceGeneratorService.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/main/java/com/ssafy/ssafsound/global/config/MongoConfig.java
  src/main/resources/static/docs/index.html
  src/test/java/com/ssafy/ssafsound/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/ssafy/ssafsound/global/docs/ControllerTest.java
  src/test/java/com/ssafy/ssafsound/global/util/fixture/NotificationFixture.java
Labels: docs, feature

#317 feat: 전체 게시글 검색 기능 구현
  src/docs/asciidoc/comment.adoc
  src/docs/asciidoc/post.adoc
  src/main/java/com/ssafy/ssafsound/domain/board/repository/BoardRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostAllSearchOffsetReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/ssafy/ssafsound/domain/post/controller/PostControllerTest.java
  src/test/java/com/ssafy/ssafsound/domain/post/service/PostServiceTest.java
  src/test/java/com/ssafy/ssafsound/global/util/fixture/PostFixture.java
Labels: docs, fix, feature
