Repository SSAF-SOUND/ssaf-sound-be, pull requests merged in 2023-06, with the labels that each got.

#5 infra: CI/CD 구축
  .github/workflows/dev-CI.yml
  .github/workflows/main-CICD.yml
  scripts/start.sh
  scripts/stop.sh
  src/appspec.yml
Labels: infra

#7 feat: 엔티티 클래스 작성
  build.gradle
  src/main/java/com/ssafy/ssafsound/SsafsoundApplication.java
  src/main/java/com/ssafy/ssafsound/domain/BaseTimeEntity.java
  src/main/java/com/ssafy/ssafsound/domain/board/domain/Board.java
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/CommentReport.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/domain/Lunch.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/domain/LunchPoll.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/AccountState.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/AlertType.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/AuthenticationStatus.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MajorType.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberAlert.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberAlertSetting.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberLink.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberLoginLog.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberProfile.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberRole.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberSkill.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberToken.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/OAuthType.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/Campus.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/Skill.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/HotPost.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/PostImage.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/PostLike.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/PostReport.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/PostScrap.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Category.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/MatchStatus.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Recruit.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitApplication.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitLimitation.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitQuestion.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitQuestionReply.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitReport.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitScrap.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitSkill.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitType.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/domain/RecruitComment.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/domain/RecruitCommentReport.java
  src/main/java/com/ssafy/ssafsound/global/common/response/EnvelopeResponse.java
Labels: feature

#9 chore: setting test coverage with JaCoCo
  build.gradle
  lombok.config
Labels: chore

#13 fix: 엔티티 클래스 멤버 변수 네이밍 수정
  src/main/java/com/ssafy/ssafsound/domain/lunch/domain/LunchPoll.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitLimitation.java
Labels: fix

#19 feat: 예외 처리
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/main/java/com/ssafy/ssafsound/global/common/exception/GlobalErrorInfo.java
  src/main/java/com/ssafy/ssafsound/global/common/response/EnvelopeResponse.java
Labels: feature

#20 feat: setting UserDto with authenticated
  src/main/java/com/ssafy/ssafsound/domain/auth/dto/AuthenticatedUser.java
  src/main/java/com/ssafy/ssafsound/domain/auth/dto/LoginRequest.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/token/JwtTokenProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/token/TokenManager.java
  src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberRepository.java
Labels: feature

#23 feat: 메타데이터 enum으로 변환
  build.gradle
  src/main/java/com/ssafy/ssafsound/domain/lunch/domain/Lunch.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberSkill.java
  src/main/java/com/ssafy/ssafsound/domain/meta/controller/MetaDataController.java
  src/main/java/com/ssafy/ssafsound/domain/meta/converter/BaseConverter.java
  src/main/java/com/ssafy/ssafsound/domain/meta/converter/CampusConverter.java
  src/main/java/com/ssafy/ssafsound/domain/meta/converter/SkillConverter.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/Campus.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/MetaData.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/MetaDataProvider.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/MetaDataType.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/Skill.java
  src/main/java/com/ssafy/ssafsound/domain/meta/dto/GetCampusesRepDto.java
  src/main/java/com/ssafy/ssafsound/domain/meta/dto/GetSkillsRepDto.java
  src/main/java/com/ssafy/ssafsound/domain/meta/exception/MetaDataIntegrityException.java
  src/main/java/com/ssafy/ssafsound/domain/meta/service/EnumMetaDataConsumer.java
  src/main/java/com/ssafy/ssafsound/domain/meta/service/MetaDataConsumer.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitSkill.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/main/java/com/ssafy/ssafsound/global/common/exception/GlobalErrorInfo.java
  src/main/java/com/ssafy/ssafsound/global/common/exception/ResourceNotFoundException.java
  src/test/java/com/ssafy/ssafsound/domain/meta/converter/BaseConverterTest.java
  src/test/java/com/ssafy/ssafsound/domain/meta/fixture/TestMetaEnum.java
  src/test/java/com/ssafy/ssafsound/domain/meta/service/EnumMetaDataConsumerTest.java
Labels: feature

#26 feat: 댓글 좋아요 엔티티 클래스 작성
  src/main/java/com/ssafy/ssafsound/domain/comment/domain/CommentLike.java
Labels: feature

#33 feat: 사용자 리크루팅 등록
  src/main/java/com/ssafy/ssafsound/domain/meta/converter/RecruitTypeConverter.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/MetaDataType.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/RecruitType.java
  src/main/java/com/ssafy/ssafsound/domain/meta/service/EnumMetaDataConsumer.java
  src/main/java/com/ssafy/ssafsound/domain/meta/validator/CheckSkills.java
  src/main/java/com/ssafy/ssafsound/domain/meta/validator/SkillsValidator.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Recruit.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitApplication.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitLimitation.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitSkill.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitType.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitLimitElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitException.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitApplicationRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitLimitationRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/validator/CheckRecruitLimitElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/validator/CheckRecruitType.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/validator/RecruitLimitElementValidator.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/validator/RecruitTypeValidator.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDtoTest.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
Labels: feature

#28 feat: 점심 메뉴 관련 API 기능 추가
  src/main/java/com/ssafy/ssafsound/domain/lunch/controller/LunchController.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/domain/Lunch.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/domain/LunchPoll.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListElementResDto.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListResDto.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchResDto.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/dto/PostLunchPollResDto.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/exception/LunchErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/exception/LunchException.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/repository/LunchPollRepository.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/repository/LunchRepository.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchService.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchServiceTest.java
Labels: feature

#27 feat: get Oauth identifier flow
  .gitignore
  build.gradle
  src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
  src/main/java/com/ssafy/ssafsound/domain/auth/domain/OauthType.java
  src/main/java/com/ssafy/ssafsound/domain/auth/dto/CreateMemberReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/auth/dto/CreateMemberTokensResDto.java
  src/main/java/com/ssafy/ssafsound/domain/auth/dto/LoginRequest.java
  src/main/java/com/ssafy/ssafsound/domain/auth/exception/AuthException.java
  src/main/java/com/ssafy/ssafsound/domain/auth/exception/MemberErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/AuthService.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/AppleOauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/GithubOauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/GoogleOauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/KakaoOauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/OauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/OauthProviderFactory.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/token/JwtTokenProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/token/TokenManager.java
  src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/main/java/com/ssafy/ssafsound/global/config/resttemplate/RestTemplateConfig.java
  src/main/resources/application-local.yml
Labels: feature

#43 feat: 사용자 / 등록자 리크루팅 QNA CUD
  src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/controller/RecruitCommentController.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/domain/RecruitComment.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/PatchRecruitCommentReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/PostRecruitCommentReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/PostRecruitCommentResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/repository/RecruitCommentRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentService.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/test/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentServiceTest.java
Labels: feature

#44 feat: create member with token
  .gitignore
  build.gradle
  src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
  src/main/java/com/ssafy/ssafsound/domain/auth/domain/OauthType.java
  src/main/java/com/ssafy/ssafsound/domain/auth/dto/AuthenticatedMember.java
  src/main/java/com/ssafy/ssafsound/domain/auth/exception/MemberErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/AuthService.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/AppleOauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/GithubOauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/GoogleOauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/KakaoOauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/OauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/OauthProviderFactory.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/token/JwtTokenProvider.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/controller/LunchController.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/OAuthType.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/PostMemberReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberException.java
  src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberRoleRepository.java
  src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/main/resources/application-local.yml
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
Labels: feature

#45 feat: 게시판 목록 조회 기능 구현
  .gitignore
  src/main/java/com/ssafy/ssafsound/domain/board/controller/BoardController.java
  src/main/java/com/ssafy/ssafsound/domain/board/dto/GetBoardListResDto.java
  src/main/java/com/ssafy/ssafsound/domain/board/dto/GetBoardResDto.java
  src/main/java/com/ssafy/ssafsound/domain/board/repository/BoardRepository.java
  src/main/java/com/ssafy/ssafsound/domain/board/service/BoardService.java
  src/main/resources/application-local.yml
Labels: feature

#50 feat: 리크루팅 관련 좋아요 기능
  src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/OauthProviderFactory.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/token/JwtTokenProvider.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/OAuthType.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/PostMemberReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitScrapRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/controller/RecruitCommentController.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/domain/RecruitCommentLike.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/repository/RecruitCommentLikeRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentService.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentServiceTest.java
Labels: feature

#52 feat: S3 스토리지 연결 #29
  .gitignore
  build.gradle
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/MetaDataType.java
  src/main/java/com/ssafy/ssafsound/domain/meta/domain/UploadDirectory.java
  src/main/java/com/ssafy/ssafsound/domain/meta/service/EnumMetaDataConsumer.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/main/java/com/ssafy/ssafsound/infra/config/S3Config.java
  src/main/java/com/ssafy/ssafsound/infra/exception/InfraErrorInfo.java
  src/main/java/com/ssafy/ssafsound/infra/exception/InfraException.java
  src/main/java/com/ssafy/ssafsound/infra/storage/service/AwsS3StorageService.java
  src/main/java/com/ssafy/ssafsound/infra/storage/service/StorageService.java
  src/main/resources/application-local.yml
Labels: feature, infra

#53 fix: 점심 조회 API 날짜 포맷 변경
  src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListReqDto.java
Labels: fix

#54 feat: AuthenticatedMember Custom Resolver With Interceptor
  src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
  src/main/java/com/ssafy/ssafsound/domain/auth/exception/MemberErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/token/JwtTokenProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/validator/Authentication.java
  src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthenticationArgumentResolver.java
  src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthorizationExtractor.java
  src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberTokenRepository.java
  src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
  src/main/java/com/ssafy/ssafsound/global/config/WebMvcConfig.java
  src/main/java/com/ssafy/ssafsound/global/interceptor/AuthInterceptor.java
Labels: feature

#56 feat: 게시글 목록 조회 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/board/exception/BoardErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/board/exception/BoardException.java
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostListResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/post/exception/PostException.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feature

#57 feat: 사용자, 등록자 리크루팅 신청 상태 변경
  src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/MatchStatus.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Recruit.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitQuestionReply.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitApplicationRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitQuestReplyRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/domain/MatchStatus.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/domain/RecruitApplication.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/PostRecruitApplicationReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/validator/RecruitApplicationValidator.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/controller/RecruitCommentController.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
Labels: feature

#64 feat: member logout with reIssue token
  src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
  src/main/java/com/ssafy/ssafsound/domain/auth/dto/CreateMemberAccessTokenResDto.java
  src/main/java/com/ssafy/ssafsound/domain/auth/exception/AuthErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/auth/exception/AuthException.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/AuthService.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/CookieProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/GithubOauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/GoogleOauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/KakaoOauthProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/OauthProviderFactory.java
  src/main/java/com/ssafy/ssafsound/domain/auth/service/token/JwtTokenProvider.java
  src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthorizationExtractor.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberToken.java
  src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberException.java
  src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
  src/main/java/com/ssafy/ssafsound/global/interceptor/AuthInterceptor.java
Labels: feature

#67 fix: 리크루트 신청 로직 수정
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitLimitation.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitQuestionReplyRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/domain/MatchStatus.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/domain/RecruitApplication.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/PostRecruitApplicationReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
  src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
Labels: fix, test

#65 feat: 게시글 스크랩 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostScrapRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
Labels: feature

#73 fix: 코드 중복 및 코드누락 수정
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
Labels: fix

#70 feat: 리크루팅 디테일 조회 기능
  src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Recruit.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitLimitElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitSkillElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitParticipantsResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/controller/RecruitCommentController.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/domain/RecruitComment.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/GetRecruitCommentsResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/RecruitCommentElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/repository/RecruitCommentRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentService.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentServiceTest.java
Labels: feature

#78 feat: member post information
  src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
  src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberResDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/dto/PostMemberInfoReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberRepository.java
  src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
  src/main/java/com/ssafy/ssafsound/domain/member/validator/Semester.java
  src/main/java/com/ssafy/ssafsound/domain/member/validator/SemesterValidator.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
Labels: feature

#79 feat: 등록자 리크루팅 신청 목록 조회 기능
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/domain/RecruitApplication.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitApplicationsResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitApplicationElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
  src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
Labels: feature

#83 feat: 게시글 작성 기능 구현
  build.gradle
  src/main/java/com/ssafy/ssafsound/domain/meta/dto/UploadFileInfo.java
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/PostImage.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostDetailResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostListResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostResDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/ImagePath.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/ImageUrl.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/PostPostWriteReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostImageRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
  src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
  src/main/java/com/ssafy/ssafsound/global/common/exception/GlobalErrorInfo.java
  src/main/java/com/ssafy/ssafsound/global/validator/CheckFileCount.java
  src/main/java/com/ssafy/ssafsound/global/validator/CheckFileSize.java
  src/main/java/com/ssafy/ssafsound/global/validator/CheckImage.java
  src/main/java/com/ssafy/ssafsound/global/validator/FileCountValidator.java
  src/main/java/com/ssafy/ssafsound/global/validator/FileSizeValidator.java
  src/main/java/com/ssafy/ssafsound/global/validator/ImageValidator.java
  src/main/java/com/ssafy/ssafsound/infra/storage/service/AwsS3StorageService.java
  src/main/java/com/ssafy/ssafsound/infra/storage/service/StorageService.java
  src/main/resources/application-local.yml
Labels: feature

#84 feat: 게시글 신고 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/PostPostReportReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostReportRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
Labels: feature

#85 feat: 등록자 리크루트 수정 삭제
  src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Recruit.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PatchRecruitReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDtoTest.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
Labels: feature

#90 refactor: 리크루트 데이터 베이스 컬럼 추가 사항 반영
  src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Recruit.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PatchRecruitReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitLimitElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitParticipantsResDto.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
  src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
  src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
  src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
Labels: refactor

#89 fix: 점심 메뉴 api 업데이트
  src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthenticationArgumentResolver.java
  src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthorizationExtractor.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/controller/LunchController.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListResDto.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/exception/LunchErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/repository/LunchPollRepository.java
  src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchService.java
  src/main/resources/application-local.yml
Labels: fix, feature

#91 feat: 게시글 수정 기능 구현
  src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
  src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
  src/main/java/com/ssafy/ssafsound/domain/post/dto/PostPutUpdateReqDto.java
  src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
  src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
  src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
Labels: feature
